/**
 * チャートパターン検出設定
 *
 * Thomas Bulkowski『Encyclopedia of Chart Patterns』に基づくパラメータ
 */

// detectChartPatterns エントリーポイントの最小データ数
export const CHART_PATTERNS_MIN_DATA = 10;

// ローカル極値検出のデフォルトウィンドウサイズ
export const CHART_PATTERN_WINDOW_SIZE = 3;

// 価格相似度のデフォルト許容度
export const DEFAULT_PRICE_TOLERANCE = 0.03;

// 各パターンの設定
export const PATTERN_CONFIG = {
  inverse_head_and_shoulders: {
    minDataPoints: 15,
    extremeWindow: 2,
    shoulderTolerance: 0.05,
    winRate: 89,
    rank: "S" as const,
    strength: { breakout: 95, noBreakout: 80 },
    confidence: { breakout: 0.85, noBreakout: 0.65 },
  },
  double_bottom: {
    minDataPoints: 10,
    extremeWindow: 2,
    priceTolerance: 0.04,
    minPeakDistance: 5,
    winRate: 88,
    rank: "S" as const,
    strength: { breakout: 92, noBreakout: 78 },
    confidence: { breakout: 0.82, noBreakout: 0.62 },
  },
  bull_flag: {
    minDataPoints: 15,
    minPoleRise: 0.05,
    minFlagLength: 5,
    flagSlopeMax: 0.001,
    flagSlopeMin: -0.005,
    maxFlagRange: 0.10,
    poleEndRatio: 0.5,
    poleLookback: 10,
    winRate: 54,
    rank: "B" as const,
    strength: { breakout: 58, noBreakout: 58 },
    confidence: { breakout: 0.50, noBreakout: 0.50 },
  },
  ascending_triangle: {
    minDataPoints: 15,
    extremeWindow: 2,
    peakSlopeMax: 0.003,
    troughSlopeMin: 0.001,
    winRate: 83,
    rank: "A" as const,
    strength: { breakout: 85, noBreakout: 70 },
    confidence: { breakout: 0.75, noBreakout: 0.55 },
  },
  triple_bottom: {
    minDataPoints: 20,
    extremeWindow: 2,
    priceTolerance: 0.04,
    minMiddlePeaks: 2,
    winRate: 87,
    rank: "A" as const,
    strength: { breakout: 88, noBreakout: 72 },
    confidence: { breakout: 0.78, noBreakout: 0.58 },
  },
  double_top: {
    minDataPoints: 10,
    extremeWindow: 2,
    priceTolerance: 0.04,
    minPeakDistance: 5,
    winRate: 73,
    rank: "B" as const,
    strength: { breakout: 78, noBreakout: 65 },
    confidence: { breakout: 0.70, noBreakout: 0.55 },
  },
  head_and_shoulders: {
    minDataPoints: 15,
    extremeWindow: 2,
    shoulderTolerance: 0.05,
    winRate: 89,
    rank: "S" as const,
    strength: { breakout: 95, noBreakout: 80 },
    confidence: { breakout: 0.85, noBreakout: 0.65 },
  },
  bear_flag: {
    minDataPoints: 15,
    minPoleDrop: 0.05,
    minFlagLength: 5,
    flagSlopeMin: -0.001,
    flagSlopeMax: 0.005,
    maxFlagRange: 0.10,
    poleEndRatio: 0.5,
    poleLookback: 10,
    winRate: 54,
    rank: "B" as const,
    strength: { breakout: 58, noBreakout: 58 },
    confidence: { breakout: 0.50, noBreakout: 0.50 },
  },
  descending_triangle: {
    minDataPoints: 15,
    extremeWindow: 2,
    troughSlopeMax: 0.003,
    peakSlopeMin: -0.001,
    winRate: 87,
    rank: "S" as const,
    strength: { breakout: 90, noBreakout: 75 },
    confidence: { breakout: 0.82, noBreakout: 0.60 },
  },
  box_range: {
    minDataPoints: 15,
    extremeWindow: 2,
    maxStdDev: 0.03,
    minRangeWidth: 0.03,
    maxRangeWidth: 0.15,
    winRate: 55,
    rank: "B" as const,
    strength: { breakout: 55, noBreakout: 55 },
    confidence: { breakout: 0.55, noBreakout: 0.55 },
  },
  symmetrical_triangle: {
    minDataPoints: 15,
    extremeWindow: 2,
    peakSlopeMax: -0.0005,
    troughSlopeMin: 0.0005,
    winRate: 55,
    rank: "B" as const,
    strength: { breakout: 55, noBreakout: 55 },
    confidence: { breakout: 0.52, noBreakout: 0.52 },
  },
  cup_with_handle: {
    minDataPoints: 20,
    cupEndRatio: 0.75,
    cupBottomMargin: 3,
    minCupDepth: 0.05,
    maxCupDepth: 0.35,
    rimRecovery: 0.90,
    maxHandleDropRatio: 0.5,
    minHandleDrop: 0.01,
    minHandleLength: 3,
    winRate: 68,
    rank: "B" as const,
    strength: { breakout: 75, noBreakout: 62 },
    confidence: { breakout: 0.65, noBreakout: 0.50 },
  },
  saucer_bottom: {
    minDataPoints: 20,
    minSlope: 0.0002,
    maxSlope: 0.008,
    minDepth: 0.02,
    maxDepth: 0.20,
    minRecovery: 0.85,
    winRate: 65,
    rank: "B" as const,
    strength: { breakout: 70, noBreakout: 58 },
    confidence: { breakout: 0.62, noBreakout: 0.48 },
  },
  inverse_cup_with_handle: {
    minDataPoints: 20,
    cupEndRatio: 0.75,
    cupTopMargin: 3,
    minCupHeight: 0.05,
    maxCupHeight: 0.35,
    rimMax: 1.10,
    maxHandleRiseRatio: 0.5,
    minHandleRise: 0.01,
    minHandleLength: 3,
    winRate: 68,
    rank: "B" as const,
    strength: { breakout: 75, noBreakout: 62 },
    confidence: { breakout: 0.65, noBreakout: 0.50 },
  },
  saucer_top: {
    minDataPoints: 20,
    minSlope: 0.0002,
    maxSlope: 0.008,
    minHeight: 0.02,
    maxHeight: 0.20,
    maxEndPriceRatio: 1.15,
    winRate: 65,
    rank: "B" as const,
    strength: { breakout: 70, noBreakout: 58 },
    confidence: { breakout: 0.62, noBreakout: 0.48 },
  },
  falling_wedge: {
    minDataPoints: 15,
    extremeWindow: 2,
    minSlope: -0.0005,
    winRate: 58,
    rank: "B" as const,
    strength: { breakout: 65, noBreakout: 52 },
    confidence: { breakout: 0.55, noBreakout: 0.42 },
  },
  rising_wedge: {
    minDataPoints: 15,
    extremeWindow: 2,
    minSlope: 0.0005,
    winRate: 58,
    rank: "B" as const,
    strength: { breakout: 65, noBreakout: 52 },
    confidence: { breakout: 0.55, noBreakout: 0.42 },
  },
} as const;
